/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SupabaseExampleImport } from './routes/supabaseExample'
import { Route as ReactQueryExampleImport } from './routes/reactQueryExample'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SupabaseExampleRoute = SupabaseExampleImport.update({
  id: '/supabaseExample',
  path: '/supabaseExample',
  getParentRoute: () => rootRoute,
} as any)

const ReactQueryExampleRoute = ReactQueryExampleImport.update({
  id: '/reactQueryExample',
  path: '/reactQueryExample',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/reactQueryExample': {
      id: '/reactQueryExample'
      path: '/reactQueryExample'
      fullPath: '/reactQueryExample'
      preLoaderRoute: typeof ReactQueryExampleImport
      parentRoute: typeof rootRoute
    }
    '/supabaseExample': {
      id: '/supabaseExample'
      path: '/supabaseExample'
      fullPath: '/supabaseExample'
      preLoaderRoute: typeof SupabaseExampleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reactQueryExample': typeof ReactQueryExampleRoute
  '/supabaseExample': typeof SupabaseExampleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reactQueryExample': typeof ReactQueryExampleRoute
  '/supabaseExample': typeof SupabaseExampleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reactQueryExample': typeof ReactQueryExampleRoute
  '/supabaseExample': typeof SupabaseExampleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/reactQueryExample' | '/supabaseExample'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/reactQueryExample' | '/supabaseExample'
  id: '__root__' | '/' | '/about' | '/reactQueryExample' | '/supabaseExample'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ReactQueryExampleRoute: typeof ReactQueryExampleRoute
  SupabaseExampleRoute: typeof SupabaseExampleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ReactQueryExampleRoute: ReactQueryExampleRoute,
  SupabaseExampleRoute: SupabaseExampleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/reactQueryExample",
        "/supabaseExample"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/reactQueryExample": {
      "filePath": "reactQueryExample.tsx"
    },
    "/supabaseExample": {
      "filePath": "supabaseExample.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
